# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20161030_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_ref',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
