# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20161031_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='room_id',
            new_name='roo',
        ),
    ]
