# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20161101_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='roo',
            new_name='room',
        ),
    ]
