# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20161101_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
