# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20161101_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_avaliability',
        ),
    ]
