# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_rooms_room_avaliability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='duration',
        ),
    ]
