# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_bookings_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='contact',
            field=models.CharField(default='d', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
