# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20161108_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_ref',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
