# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20161108_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(),
        ),
    ]
