# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20161217_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('reservations_id', models.IntegerField(primary_key=True, serialize=False)),
                ('expiry', models.TimeField(default=datetime.datetime.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.rooms')),
            ],
        ),
    ]
