# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20161219_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservations_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
