# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20161219_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
