# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('booking_ref', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('contact', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='recurringEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurrence', models.CharField(choices=[(b'1', b'Daily'), (b'2', b'Weekly'), (b'3', b'Biweekly')], max_length=10)),
            ],
            options={
                'db_table': 'recurringEvents',
            },
        ),
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=60)),
                ('room_size', models.IntegerField()),
                ('room_location', models.TextField()),
                ('room_features', models.TextField()),
                ('in_use', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('passcode', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='reservations',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AddField(
            model_name='recurringevents',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='recurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bksys.recurringEvents'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.User'),
        ),
    ]
