# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=254)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('passcode', models.CharField(max_length=6, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('booking_ref', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('contact', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='recurringEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurrence', models.CharField(choices=[(b'1', b'Daily'), (b'2', b'Weekly'), (b'3', b'Biweekly')], max_length=10)),
            ],
            options={
                'db_table': 'recurringEvents',
            },
        ),
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=60)),
                ('room_size', models.IntegerField()),
                ('room_location', models.TextField()),
                ('room_features', models.TextField()),
                ('in_use', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='reservations',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AddField(
            model_name='recurringevents',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='recurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bksys.recurringEvents'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
    ]
