# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='recurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bksys.recurringBookings'),
        ),
    ]
