# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
