# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0002_auto_20170310_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='recurrence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bksys.recurringEvents'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AlterField(
            model_name='recurringevents',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
    ]
