# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0002_auto_20170112_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recurringBookings',
            new_name='recurringEvents',
        ),
        migrations.RenameField(
            model_name='recurringevents',
            old_name='recurence',
            new_name='recurrence',
        ),
    ]
