# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0002_auto_20170126_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='session_id',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
