# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0003_auto_20170121_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passcode',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
