# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0003_auto_20170113_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='reservations_id',
            new_name='id',
        ),
    ]
