# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0003_auto_20170310_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringevents',
            name='room',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_features',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_location',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='users',
            name='passcode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
