# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0004_auto_20170113_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='expiry',
            new_name='start_time',
        ),
    ]
