# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0005_auto_20170310_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='recurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bksys.recurringEvents'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.users'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.rooms'),
        ),
    ]
