# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0006_auto_20170121_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
