# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0007_auto_20170121_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bksys.User'),
        ),
    ]
